### ISSUE TITLE
Mathematical operations on ArrayLength<T> possible?

### ISSUE THREAD

**Issue by ashleysommer** [fizyk20/generic-array#22] opened 2016-09-16 05:53 UTC
I've been beating around trying to get something like this to work:

```
struct Foo<N: ArrayLength<i32>> {
    data: GenericArray<i32, N>,
    index: GenericArray<i32, <N as Mul<U2>>::Output>
}
```

Basically, I want the second array to always have double the length of the first array, using only the single N generic passed in.
Im trying to use the same kind of ops provided by `typenum`, but I'm getting compiler errors like:
`trait N: core::ops::Mul<typenum::UInt<typenum::UInt<typenum::UTerm, typenum::B1>, typenum::B0>> not satisfied`
I would have assumed that since the type `ArrayLength<T>` is based on the `Unsigned` it should already have `Mul` implemented inherently.
Or am I doing something really stupid?

**Comment by fizyk20** [comment] 2016-09-16 07:02
Nothing stupid here, in fact it's quite possible - the problem is that the `ArrayLength<T>` trait doesn't imply any of the operator traits, so you will need a `where` clause:

```rust
struct Foo<N: ArrayLength<i32>> 
    where N: Mul<U2>,
               <N as Mul<U2>>::Output: ArrayLength<i32>
{
    data: GenericArray<i32, N>,
    index: GenericArray<i32, <N as Mul<U2>>::Output>
}
```

It should work this way :)

**Comment by fizyk20** [comment] 2016-12-10 14:37
Since there are no further questions, I'm closing this issue.

**Closed by fizyk20** 2016-12-10 14:37 UTC

**Comment by Pratyush** [comment] 2017-09-25 06:00
So quick question: is it possible to have a blanket impl for common operator outputs? For example `impl<N, M, T> ArrayLength<T> for Sum<N, M> where N: ArrayLength<T>, M: ArrayLength<T>`? This would reduce the `where` clause boilerplate in struct definitions (if it was possible).

**Comment by fizyk20** [comment] 2017-09-28 04:46
I'm not sure if this is possible, nor if it will actually help with the boilerplate - but you're welcome to try! ;)
